const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const dataURL = name => `data:image/webp;base64,${fs.readFileSync(path.join(root, 'assets', name)).toString('base64')}`;
let html = read('index.html');
html = html.replace('<link rel="stylesheet" href="src/style.css">', `<style>\n${read('src/style.css')}\n</style>`);
html = html.replace('src="assets/hero.webp"', `src="${dataURL('hero.webp')}"`);
html = html.replace('<script src="src/engine.js"></script>', `<script>\n${read('src/engine.js')}\n</script>`);
html = html.replace('<script src="src/game.js"></script>', `<script>window.STAR_MUNCH_ASSETS = ${JSON.stringify({ atlas: dataURL('hero-atlas.webp') })};\n${read('src/game.js')}\n</script>`);
const out = path.join(root, 'build'); fs.mkdirSync(out, { recursive: true });
const filename = path.join(out, '별냠.html'); fs.writeFileSync(filename, html);
const sha256 = crypto.createHash('sha256').update(html).digest('hex');
fs.writeFileSync(path.join(out, 'build-info.json'), JSON.stringify({ game: '별냠', version: JSON.parse(read('package.json')).version, file: '별냠.html', bytes: Buffer.byteLength(html), sha256 }, null, 2) + '\n');
console.log(`Built ${filename} (${(Buffer.byteLength(html) / 1024 / 1024).toFixed(2)} MiB)\nSHA-256 ${sha256}`);
